language: csharp
os:
  - linux
  - osx
solution: Harmony.sln
matrix:
  include:
    - dotnet:
      - 1.1.13
      - 2.1.202
      - 2.1.603
      - 2.2.203
      mono: none
    - mono:
      - 2.10.8
      - 3.2.8
      - 3.8.0
      - latest
before_install:
  - if [ "$TRAVIS_COMMIT_MESSAGE" == "Update documentation" ]; then echo "Skipping documentation only commit" && exit; fi
install:
  - nuget restore
  - dotnet restore
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe HarmonyTests/bin/Release/net45/HarmonyTests.dll