language: csharp
os:
  - linux
  - osx
solution: Harmony.sln
matrix:
  include:
    - dotnet:
      - 1.0.15
      - 1.1.12
      - 2.0.9
      - 2.1.10
      - 2.2.4
      mono: none
    - mono:
      - 2.10.8
      - 3.2.8
      - 3.8.0
      - latest
install:
  - nuget restore
  - dotnet restore
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe HarmonyTests/bin/Release/net45/HarmonyTests.dll