language: csharp
solution: Harmony.sln
matrix:
  include:

    - dotnet: 1.1.13
      os: windows
      mono: none

    - dotnet: 2.1.202
      os: windows
      mono: none

    - dotnet: 2.1.603
      os: windows
      mono: none

    - dotnet: 2.2.203
      os: windows
      mono: none

    - mono:
      - latest
      os: windows

    - mono:
      - latest
      os: linux

    - mono:
      - latest
      os: osx

before_install:
  - if [ "$TRAVIS_COMMIT_MESSAGE" == "Update documentation" ]; then echo "Skipping documentation only commit" && exit; fi
install:
  - nuget restore
  - dotnet restore
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe HarmonyTests/bin/Release/net45/HarmonyTests.dll
notifications:
  email: false