version: 1.0.{build}

max_jobs: 1
image: Visual Studio 2015
configuration: Release

before_build:
- nuget restore
- dotnet restore

build:
- verbosity: minimal

artifacts:
- path: 'Harmony\bin\Release\Lib.Harmony.*.nupkg'
